version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/frontend/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pnpm"
    directory: "/backend/"
    schedule:
      interval: "weekly"
