name: CI - backend

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.5.2
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: backend/pnpm-lock.json
          node-version: "22"
          cache: pnpm

      - name: Install Backend Dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Test Backend
        run: |
          pnpm test
