name: CI - backend

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  backend:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, windows-2025]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    defaults:
      run:
        shell: bash --noprofile --norc -eo pipefail {0}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.5.2
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: backend/pnpm-lock.yaml
          node-version: "22"
          cache: pnpm

      - name: Setup Make (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install make

      - name: Install Backend Dependencies
        run: |
          cd backend && pnpm install --frozen-lockfile

      - name: Test Backend
        run: |
          make test_be
