name: CI - frontend

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  frontend:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: frontend/package-lock.json
          node-version: "22"
          cache: pnpm

      - name: Install Frontend Dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Build Frontend
        run: |
          pnpm build

      - name: Test Frontend
        run: |
          pnpm test
