name: CI - frontend

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  frontend:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    defaults:
      run:
        shell: bash --noprofile --norc -eo pipefail {0}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.5.2
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: frontend/pnpm-lock.yaml
          node-version: "22"
          cache: pnpm

      - name: Install Frontend Dependencies
        run: |
          cd frontend && pnpm install --frozen-lockfile

      - name: Prep for Vitest Browser Mode
        run: |
          cd frontend && pnpm exec playwright install

      - name: Test Frontend
        run: |
          cd frontend && pnpm run lint && pnpm test && pnpm run build
