name: CI

on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    paths:
      - 'frontend/**'
      - 'backend/**'
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  frontend:
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, windows-2025]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    defaults:
      run:
        shell: bash --noprofile --norc -eo pipefail {0}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.5.2
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: frontend/pnpm-lock.yaml
          node-version: "22"
          cache: pnpm

      - name: Install Frontend Dependencies
        run: |
          cd frontend && pnpm install --frozen-lockfile

      - name: Setup Make (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install make

      - name: Prep for Vitest Browser Mode
        run: |
          cd frontend && pnpm exec playwright install

      - name: Test Frontend
        run: |
          make test_fe

  backend:
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, windows-2025]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    defaults:
      run:
        shell: bash --noprofile --norc -eo pipefail {0}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.5.2
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: backend/pnpm-lock.yaml
          node-version: "22"
          cache: pnpm

      - name: Setup Make (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install make

      - name: Install Backend Dependencies
        run: |
          cd backend && pnpm install --frozen-lockfile

      - name: Test Backend
        run: |
          make test_be