name: Dependabot Auto-merge
"on": pull_request

jobs:
  ci:
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: ./.github/workflows/ci.yml

  merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    needs: ci
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          gh pr review "${GITHUB_HEAD_REF}" --approve
          gh pr merge "${GITHUB_HEAD_REF}" --squash --auto
